; ---------------- Hawk01 专属格式 ----------------
[REG_CONFIG]
in_template = {val0=I2C_Write}, {val1}, {ADDR:16}, {VAL:16}
out_template = {val0}, {val1}, {ADDR:0>4X}, {VAL:0>2X}
parse_sep = ,
parse_comment_sym = //
gen_comment_sym = //
[ROISRAM_CONFIG]
in_template = {val0=I2C_Block_Write}, {val1}, {ADDR}, {LENGTH:16}, {ROISRAM_NAME}
out_template = {val0}, {val1}, {ADDR}, {LENGTH:0>3X}, {ROISRAM_NAME}
parse_sep = ,
parse_comment_sym = //
gen_comment_sym = //